---
driver:
  name: vagrant
  cachier: true

platforms:
  - name: ubuntu-20.04
    driver:
      box: ubuntu/focal64

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_verbose: true
  require_chef_for_busser: false
  playbook: test/test.yml
  ansible_apt_repo: ''

verifier:
  name: inspec

suites:
  - name: default