# tasks file for ansible-haproxy
---

- block:
  
    - name: ensure haproxy repository is added from ppa
      apt_repository:
        repo: "{{ haproxy_ppa }}"
        update_cache: true

    - name: ensure software-properties-common is installed
      apt:
        name: software-properties-common
        state: present
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no

    - name: ensure haproxy is installed
      apt:
        name: "{{ item }}"
        state: present
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
      with_items:
        - "{{ haproxy_package_name }}"
        
  become: yes
  tags:
    - haproxy
