---
# handlers file for ansible-haproxy
- name: restart haproxy
  service:
    name: haproxy
    state: "{{ haproxy_restart_handler_state }}"
  when: service_default_state | default('started') == 'started'
